# The logo that is displayed in the upper left part of the media module page. This can be eithera path or a complete url
# with scheme and port.
logo: /engage/ui/img/logo/opencast-icon.svg

# A custom URL the login button should point to.
# Can be used for aai logins, e.g. /Shibboleth.sso/Login?target=/engage/ui/index.html
# customLoginURL: