project_id: 285795
api_token_env: CROWDIN_TOKEN
base_path: .
preserve_hierarchy: true

files:
  -
    source: '/modules/engage-ui/src/main/resources/ui/language/en-US.json'
    translation: '/modules/engage-ui/src/main/resources/ui/language/%locale%.json'

  -
    source: '/modules/engage-paella-player-7/src/i18n/en-US.json'
    translation: '/modules/engage-paella-player-7/src/i18n/%locale%.json'
